### ISSUE TITLE
Variáveis final e construtores

### ISSUE THREAD

**Issue by dfpinto** [robsoncalixto/study-java#1]
Deparei-me com um construtor UserService do projeto portal do corretor onde cada atributo criado com static final era inicializado no construtor.
Escrevi muito rapidamente o lance do static final... a dúvida não era necessariamente sobre esses modificadores mas sobre a obrigação de incluir no construtor da classe UserService mais um parâmetro referente ao novo atributo criado... caso contrário dá erro de compilação... ou seja, como o compilador saber que o simples fato de incluir um atributo gera erro no construtor?

**Comment by robsoncalixto** [comment]
Esse construtor está garantindo que os atributos serão propagados para todas as instâncias desta classe. O final garante que este valor seja imutável, mas uma coisa não depende da outra.

**Comment by dfpinto** [comment]
O Tiago Sinatra me explicou que se eu declarar uma var final numa classe, obrigatoriamente terei que relacioná-la em seu construtor. Variáveis final precisam ser inicializadas já que são imutáveis e nada melhor que fazê-las na instanciação da classe, em seu construtor.
Além disso, se essa classe depender de outras, usando essa abordagem, eu poderei usar um único @Autowired no construtor ao invés de vários.
Outro motivo é a facilidade nos testes automatizados.

**Comment by dfpinto** [comment]
Segue exemplo:

@Service
public class UserService {

	private final Logger logger = LoggerFactory.getLogger(this.getClass());
	private final String urlServicoSessao;
	private final PortalCorretorService portalCorretorService;
	private final UsuarioDAO usuarioDAO;
	private final UsuarioRepository usuarioRepository;
	private final ContratoEmpresaRespository contratoEmpresaRespository;
	private final PortalUsuarioDAO portalUsuarioDAO;
	private final String authorizationCorporativo;
	private final String urlServicoToken;
	private final String urlServicoPortalLogin;
	private final String urlServicoEmail;
	private final String urlServicoConsultaSusep;

	public static final String SIM = "S";
	public static final String NAO = "N";
	public static final String ERRO_NA_RESPOSTA_DO_SERVICO = "Erro na resposta do servico";
	private static final String ERRO_NA_AUTENTICACAO = "Erro na autenticação.";
	private static final String AUTHORIZATION = "Authorization";
	private static final String COD_USER = "COD_USER";

	@Autowired
	public UserService(
			@Value("${login.authorizationCorporativo}") String authorizationCorporativo,
			@Value("${login.urlServicoSessao}") String urlServicoSessao,
			@Value("${login.urlServicoPortalLogin}") String urlServicoPortalLogin,
			@Value("${login.urlServicoToken}") String urlServicoToken,
			@Value("${login.urlServicoConsultaSusep}") String urlServicoConsultaSusep,
			PortalCorretorService portalCorretorService, UsuarioDAO usuarioDAO, @Value("${urlServicoEmail}") String urlServicoEmail, UsuarioRepository usuarioRepository, 
			ContratoEmpresaRespository contratoEmpresaRespository,
			PortalUsuarioDAO portalUsuarioDAO) {
		this.portalCorretorService = portalCorretorService;
		this.urlServicoSessao = urlServicoSessao;
		this.usuarioDAO = usuarioDAO;
		this.portalUsuarioDAO = portalUsuarioDAO;
		this.usuarioRepository = usuarioRepository;
		this.contratoEmpresaRespository = contratoEmpresaRespository;
		this.authorizationCorporativo = authorizationCorporativo;
		this.urlServicoPortalLogin = urlServicoPortalLogin;
		this.urlServicoToken = urlServicoToken;
		this.urlServicoConsultaSusep = urlServicoConsultaSusep;
	this.urlServicoEmail = urlServicoEmail;
	}
